CREATE TABLE transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_account VARCHAR(255) NOT NULL,
    destiny_account VARCHAR(255) NOT NULL,
    transfer_value DOUBLE NOT NULL,
    tax DOUBLE,
    transfer_date DATE NOT NULL,
    scheduling TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
